### ISSUE TITLE
About the issue of a too small 'leaf_size' in large-scale point cloud filtering.

### ISSUE THREAD

**Issue by ghost** [ktgiahieu/Fast-PPF#11]
Dear author, thank you for your selfless open-source contribution. While using your project, I encountered an issue with the 'leaf_size' parameter being too small during the filtering stage, which resulted in insufficient storage for voxel node data due to its 32-bit format. I would like to know if using Octree filtering would be a perfect solution to this problem. I prefer not to sacrifice accuracy to resolve this issue (typically, expanding from 0.001f to 10.0f), as I find this approach unacceptable.

**Comment by ktgiahieu** [comment]
Yes, you can. As long as you understand the key points in the filtering stage:
- I first calculated `samp_rad` (in meter) using `t_sampling` (a ratio, default = 4%) multiplies with diameter_model(the distance between 2 furthest point in your model point cloud, in meter) [here](https://github.com/ktgiahieu/Fast-PPF/blob/master/include/PPF/PPF.cpp#L118).
- Then, I down-sample the scene point cloud to `leaf_size = 0.001f`, in order to run statisticalOutlinerRemoval to remove the outlines (since there will be a lot of points in the clusters with actual information and very few points from noises outside of the cluster). Finally, I downsample it one last time to `samp_rad` (default = 4% of the model's diameter) before further calculation[here](https://github.com/ktgiahieu/Fast-PPF/blob/master/include/PPF/PPF.cpp#L219-L229)

As long as your new `leaf_size` is still small enough for the function `statisticalOutlinerRemoval` to filter noises properly, and your new `leaf_size` <= `samp_rad`, any filtering method should work.

Good luck!
