### ISSUE TITLE
Code questions

### ISSUE THREAD

**Issue by chengm0-0** [ktgiahieu/Fast-PPF#2]
Hello, why do you take visual points from six perspectives in the code? I don't think the paper mentioned different perspectives. Is there any advantage in doing so? Thank you!

**Comment by ktgiahieu** [comment]
Yeah it is an inspiration to remove internal points of the object, which aligns better with real world data since you cannot "see" internal points with the camera. In my case, this preprocess really helps the output. I guess the original author did use some kind of preprocess too, but not mentioned specifically in the paper.

**Comment by chengm0-0** [comment]
If only the point cloud of the surface is extracted for a part, can this preprocessing be avoided?

**Comment by ktgiahieu** [comment]
Sure, it is.
